export const BOOKING_FLOW_ACTIONS = {
  // Step management
  SET_STEP: 'SET_STEP',
  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
  RESET_TO_STEP: 'RESET_TO_STEP',

  // Address
  SET_ADDRESS: 'SET_ADDRESS',
  CLEAR_ADDRESS: 'CLEAR_ADDRESS',

  // Categories and waste types
  SET_SELECTED_CATEGORIES: 'SET_SELECTED_CATEGORIES',
  ADD_CATEGORY: 'ADD_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  SET_SELECTED_WASTE_TYPES: 'SET_SELECTED_WASTE_TYPES',
  ADD_WASTE_TYPE: 'ADD_WASTE_TYPE',
  REMOVE_WASTE_TYPE: 'REMOVE_WASTE_TYPE',

  // Heavy waste
  SET_HAS_HEAVY_WASTE: 'SET_HAS_HEAVY_WASTE',
  SET_HEAVY_WASTE_TYPES: 'SET_HEAVY_WASTE_TYPES',
  ADD_HEAVY_WASTE_TYPE: 'ADD_HEAVY_WASTE_TYPE',
  REMOVE_HEAVY_WASTE_TYPE: 'REMOVE_HEAVY_WASTE_TYPE',
  SET_HEAVY_WASTE_PERCENTAGE_RANGE: 'SET_HEAVY_WASTE_PERCENTAGE_RANGE',
  SET_PLASTERBOARD_PERCENTAGE_RANGE: 'SET_PLASTERBOARD_PERCENTAGE_RANGE',

  // Skip and bags
  SET_SELECTED_SKIP: 'SET_SELECTED_SKIP',
  SET_TONNE_BAGS: 'SET_TONNE_BAGS',

  // Permit
  SET_NEEDS_PERMIT: 'SET_NEEDS_PERMIT',
  SET_PERMIT_INFO: 'SET_PERMIT_INFO',

  // Dates
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  SET_SELECTED_COLLECTION_DATE: 'SET_SELECTED_COLLECTION_DATE',

  // Completion
  SET_POPS_COMPLETED: 'SET_POPS_COMPLETED',

  // Reset and update
  RESET_FORM: 'RESET_FORM',
  UPDATE_FORM: 'UPDATE_FORM',
} as const
